### ISSUE TITLE
DISCUSS: Refer to RFC5245 vice 5245-bis

### ISSUE THREAD

**Issue by seanturner** [rtcweb-wg/rtcweb-overview#36]
EKR entered the following DISCUSS:

    Your citation to ICE is to 5245-bis, but at least
    the JSEP editor consensus was that WebRTC
    depended on 5245, so this needs to be resolved
    one way or the other.

**Comment by alvestrand** [comment]
Sean asked me to leave this one open. Personally, I'd somewhat prefer to 5245bis because it separates out the SDP machinery, but JSEP has a specific section reference (section 15.4) that has to go to either 5245 or to mmusic-ice-sip-sdp, and one could argue that we need to pull in -sip-sdp here too.

I'm OK with 5245 as a reference, but will let the chairs make the call.
